package server

import (
	"encoding/hex"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/gin-gonic/gin"

	"gitlab.dev.ihuman.com/ihuman-infrastructure/dev/galaxy/common/redis-pilot/pkg/apitypes"
)

var envoyTmpl = template.Must(template.New("envoy").Parse(`# Auto-generated by redis-pilot server. DO NOT EDIT.
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
{{- range .Listeners }}
  - name: {{ .Name }}
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Port }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: {{ .StatPrefix }}
          settings:
            op_timeout: 5s
            read_policy: {{ .ReadPolicy }}
{{- if .Password }}
          downstream_auth_password:
            inline_string: "{{ .Password }}"
{{- end }}
          prefix_routes:
            catch_all_route:
              cluster: {{ .Cluster }}
{{- end }}

  clusters:
{{- range .Clusters }}
  - name: {{ .Name }}
    type: STRICT_DNS
{{- if .HealthCheckRole }}
    health_checks:
    - timeout: 1s
      interval: 5s
      unhealthy_threshold: 2
      healthy_threshold: 1
      tcp_health_check:
        send:
          text: {{ .HealthCheckPayload }}
        receive:
        - text: {{ .RoleResponsePrefix }}
{{- end }}
{{- if .Password }}
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
        auth_password:
          inline_string: "{{ .Password }}"
{{- end }}
    load_assignment:
      cluster_name: {{ .Name }}
      endpoints:
      - lb_endpoints:
{{- range .Endpoints }}
        - endpoint:
            address:
              socket_address:
                address: {{ .Address }}
                port_value: {{ .Port }}
{{- end }}
{{- end }}
`))

type envoyListener struct {
	Name       string
	Port       int
	StatPrefix string
	Cluster    string
	Password   string
	ReadPolicy string
}

type envoyEndpoint struct {
	Address string
	Port    int
}

type envoyCluster struct {
	Name               string
	Password           string
	HealthCheckRole    string
	HealthCheckPayload string
	RoleResponsePrefix string
	Endpoints          []envoyEndpoint
}

type envoyData struct {
	Listeners []envoyListener
	Clusters  []envoyCluster
}

func (s *Server) envoyRouteUpdate(c *gin.Context) {
	config, err := s.generateEnvoyConfig()
	if err != nil {
		fail(c, http.StatusInternalServerError, err.Error())
		return
	}
	if s.cfg.EnvoyDir != "" {
		if err := s.writeEnvoyConfig(config); err != nil {
			fail(c, http.StatusInternalServerError, "write envoy config: "+err.Error())
			return
		}
		s.reloadEnvoy()
	}
	ok(c, gin.H{"config": config})
}

func (s *Server) envoyConfig(c *gin.Context) {
	config, err := s.generateEnvoyConfig()
	if err != nil {
		fail(c, http.StatusInternalServerError, err.Error())
		return
	}
	ok(c, gin.H{"config": config})
}

// generateEnvoyConfig 根据 instances-state 和 pool-state 生成 Envoy 配置
func (s *Server) generateEnvoyConfig() (string, error) {
	instances, err := s.state.ReadInstances()
	if err != nil {
		return "", err
	}
	pool, err := s.state.ReadPool()
	if err != nil {
		return "", err
	}

	// 按稳定实例组聚合
	groups := s.buildInstanceGroups(instances, pool)

	data := envoyData{}
	for groupName, g := range groups {
		rwClusterName := "redis-" + groupName + "-cluster"
		writeClusterName := "redis-" + groupName + "-write-cluster"
		statPrefix := "redis_" + strings.ReplaceAll(groupName, "-", "_")

		if g.rwPort > 0 {
			data.Listeners = append(data.Listeners, envoyListener{
				Name:       "redis-" + groupName + "-rw",
				Port:       g.rwPort,
				StatPrefix: statPrefix,
				Cluster:    rwClusterName,
				Password:   g.password,
				ReadPolicy: g.rwReadPolicy(),
			})
		}

		if g.woPort > 0 {
			data.Listeners = append(data.Listeners, envoyListener{
				Name:       "redis-" + groupName + "-wo",
				Port:       g.woPort,
				StatPrefix: statPrefix + "_wo",
				Cluster:    writeClusterName,
				Password:   g.password,
				ReadPolicy: "MASTER",
			})
		}

		if len(g.endpoints) > 0 {
			data.Clusters = append(data.Clusters, envoyCluster{
				Name:      rwClusterName,
				Password:  g.password,
				Endpoints: g.endpoints,
			})
			if g.woPort > 0 {
				data.Clusters = append(data.Clusters, envoyCluster{
					Name:               writeClusterName,
					Password:           g.password,
					HealthCheckRole:    "master",
					HealthCheckPayload: roleHealthCheckPayload(g.password),
					RoleResponsePrefix: "\"" + hex.EncodeToString([]byte("*3\r\n$6\r\nmaster\r\n")) + "\"",
					Endpoints:          g.endpoints,
				})
			}
		}
	}

	var buf strings.Builder
	if err := envoyTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

type instanceGroup struct {
	rwPort     int // 读写端口
	woPort     int // 仅写端口
	password   string
	endpoints  []envoyEndpoint
	hasReplica bool
}

func (g *instanceGroup) rwReadPolicy() string {
	if g.hasReplica {
		return "REPLICA"
	}
	return "MASTER"
}

func roleHealthCheckPayload(password string) string {
	var raw string
	if password == "" {
		raw = "*1\r\n$4\r\nROLE\r\n"
	} else {
		raw = fmt.Sprintf("*2\r\n$4\r\nAUTH\r\n$%d\r\n%s\r\n*1\r\n$4\r\nROLE\r\n", len(password), password)
	}
	return "\"" + hex.EncodeToString([]byte(raw)) + "\""
}

// buildInstanceGroups 按稳定实例组聚合，提取 Envoy 端口和后端地址
func (s *Server) buildInstanceGroups(instances *apitypes.InstancesState, pool *apitypes.PoolState) map[string]*instanceGroup {
	groups := make(map[string]*instanceGroup)

	for name, inst := range instances.Instances {
		if inst.Status != "running" {
			continue
		}

		groupName := inst.Group
		if groupName == "" {
			// 兼容旧状态：主库用自己的名字，从库找主库名
			groupName = name
		}
		if inst.Role == "replica" && inst.Group == "" {
			// 从主库的 Replicas 列表反查
			for mName, mInst := range instances.Instances {
				for _, r := range mInst.Replicas {
					if r == name {
						groupName = mName
						break
					}
				}
			}
		}

		g, ok := groups[groupName]
		if !ok {
			// 只有配置了 Envoy 的实例组才创建
			if inst.Envoy == nil && inst.Role != "replica" {
				continue
			}
			g = &instanceGroup{}
			groups[groupName] = g
		}

		// 端口取主库/standalone 的 Envoy 配置（从库没有 Envoy 字段）
		if inst.Envoy != nil && (inst.Role == "master" || inst.Role == "standalone") {
			if inst.Envoy.ReadWritePort > 0 {
				g.rwPort = inst.Envoy.ReadWritePort
			}
			if inst.Envoy.WriteOnlyPort > 0 {
				g.woPort = inst.Envoy.WriteOnlyPort
			}
			g.password = inst.Password
		}

		// 后端地址：主库和从库都加入 endpoints
		srv := pool.Servers[inst.Server]
		if srv != nil {
			g.endpoints = append(g.endpoints, envoyEndpoint{
				Address: srv.Endpoint,
				Port:    inst.Port,
			})
		}
		if inst.Role == "replica" {
			g.hasReplica = true
		}
	}

	return groups
}

func (s *Server) writeEnvoyConfig(config string) error {
	if err := os.MkdirAll(s.cfg.EnvoyDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(s.cfg.EnvoyDir, "envoy-redis.yaml"), []byte(config), 0644)
}

// refreshEnvoy 拓扑变更后自动刷新 Envoy 配置（静默失败，不影响主操作）
func (s *Server) refreshEnvoy() {
	if s.cfg.EnvoyDir == "" {
		return
	}
	config, err := s.generateEnvoyConfig()
	if err != nil {
		s.log.Errorf("envoy config generate failed: %v", err)
		return
	}
	if err := s.writeEnvoyConfig(config); err != nil {
		s.log.Errorf("envoy config write failed: %v", err)
		return
	}
	s.log.Infof("envoy config updated: %s", fmt.Sprintf("%s/envoy-redis.yaml", s.cfg.EnvoyDir))
	s.reloadEnvoy()
}

// reloadEnvoy 执行用户配置的重载命令（静默失败）
func (s *Server) reloadEnvoy() {
	if s.cfg.EnvoyReloadCmd == "" {
		return
	}
	out, err := exec.Command("sh", "-c", s.cfg.EnvoyReloadCmd).CombinedOutput()
	if err != nil {
		s.log.Errorf("envoy reload failed: %v, output: %s", err, string(out))
		return
	}
	s.log.Infof("envoy reloaded via: %s", s.cfg.EnvoyReloadCmd)
}
