package server

import (
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/gin-gonic/gin"

	"gitlab.dev.ihuman.com/ihuman-infrastructure/dev/galaxy/common/redis-pilot/pkg/apitypes"
)

var envoyTmpl = template.Must(template.New("envoy").Parse(`# Auto-generated by redis-pilot server. DO NOT EDIT.
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
{{- range .Listeners }}
  - name: {{ .Name }}
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Port }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: {{ .StatPrefix }}
          settings:
            op_timeout: 5s
            read_policy: {{ .ReadPolicy }}
{{- if .Password }}
          downstream_auth_password:
            inline_string: "{{ .Password }}"
{{- end }}
          prefix_routes:
            catch_all_route:
              cluster: {{ .Cluster }}
{{- if .ReadCluster }}
              read_command_policy:
                cluster: {{ .ReadCluster }}
{{- end }}
{{- end }}

  clusters:
{{- range .Clusters }}
  - name: {{ .Name }}
    type: STRICT_DNS
{{- if .HealthCheckRole }}
    health_checks:
    - timeout: 1s
      interval: 5s
      unhealthy_threshold: 2
      healthy_threshold: 1
      tcp_health_check:
        send:
          text: {{ .HealthCheckPayload }}
        receive:
        - text: {{ .RoleResponsePrefix }}
{{- end }}
{{- if .Password }}
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
        auth_password:
          inline_string: "{{ .Password }}"
{{- end }}
    load_assignment:
      cluster_name: {{ .Name }}
      endpoints:
      - lb_endpoints:
{{- range .Endpoints }}
        - endpoint:
            address:
              socket_address:
                address: {{ .Address }}
                port_value: {{ .Port }}
{{- end }}
{{- end }}
`))

type envoyListener struct {
	Name        string
	Port        int
	StatPrefix  string
	Cluster     string
	ReadCluster string
	Password    string
	ReadPolicy  string
}

type envoyEndpoint struct {
	Address string
	Port    int
}

type envoyCluster struct {
	Name               string
	Password           string
	HealthCheckRole    string
	HealthCheckPayload string
	RoleResponsePrefix string
	Endpoints          []envoyEndpoint
}

type envoyData struct {
	Listeners []envoyListener
	Clusters  []envoyCluster
}

func (s *Server) envoyRouteUpdate(c *gin.Context) {
	config, err := s.generateEnvoyConfig()
	if err != nil {
		fail(c, http.StatusInternalServerError, err.Error())
		return
	}
	if s.cfg.EnvoyDir != "" {
		if err := s.writeEnvoyConfig(config); err != nil {
			fail(c, http.StatusInternalServerError, "write envoy config: "+err.Error())
			return
		}
		s.reloadEnvoy()
	}
	ok(c, gin.H{"config": config})
}

func (s *Server) envoyConfig(c *gin.Context) {
	config, err := s.generateEnvoyConfig()
	if err != nil {
		fail(c, http.StatusInternalServerError, err.Error())
		return
	}
	ok(c, gin.H{"config": config})
}

// generateEnvoyConfig 根据 instances-state 和 pool-state 生成 Envoy 配置
func (s *Server) generateEnvoyConfig() (string, error) {
	instances, err := s.state.ReadInstances()
	if err != nil {
		return "", err
	}
	pool, err := s.state.ReadPool()
	if err != nil {
		return "", err
	}

	// 按稳定实例组聚合
	groups := s.buildInstanceGroups(instances, pool)

	data := envoyData{}
	for groupName, g := range groups {
		masterClusterName := "redis-" + groupName + "-master-cluster"
		replicaClusterName := "redis-" + groupName + "-replica-cluster"
		statPrefix := "redis_" + strings.ReplaceAll(groupName, "-", "_")

		if g.masterPort > 0 && len(g.masterEndpoints) > 0 {
			data.Listeners = append(data.Listeners, envoyListener{
				Name:       "redis-" + groupName + "-master",
				Port:       g.masterPort,
				StatPrefix: statPrefix + "_master",
				Cluster:    masterClusterName,
				Password:   g.password,
				ReadPolicy: "MASTER",
			})
		}

		if g.autoPort > 0 && len(g.masterEndpoints) > 0 && len(g.replicaEndpoints) > 0 {
			data.Listeners = append(data.Listeners, envoyListener{
				Name:        "redis-" + groupName + "-auto",
				Port:        g.autoPort,
				StatPrefix:  statPrefix + "_auto",
				Cluster:     masterClusterName,
				ReadCluster: replicaClusterName,
				Password:    g.password,
				ReadPolicy:  "MASTER",
			})
		}

		if len(g.masterEndpoints) > 0 {
			data.Clusters = append(data.Clusters, envoyCluster{
				Name:      masterClusterName,
				Password:  g.password,
				Endpoints: g.masterEndpoints,
			})
		}
		if g.autoPort > 0 && len(g.replicaEndpoints) > 0 {
			data.Clusters = append(data.Clusters, envoyCluster{
				Name:      replicaClusterName,
				Password:  g.password,
				Endpoints: g.replicaEndpoints,
			})
		}
	}

	var buf strings.Builder
	if err := envoyTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

type instanceGroup struct {
	autoPort         int
	masterPort       int
	password         string
	masterEndpoints  []envoyEndpoint
	replicaEndpoints []envoyEndpoint
}

// buildInstanceGroups 按稳定实例组聚合，提取 Envoy 端口和后端地址
func (s *Server) buildInstanceGroups(instances *apitypes.InstancesState, pool *apitypes.PoolState) map[string]*instanceGroup {
	groups := make(map[string]*instanceGroup)

	for groupName, group := range instances.Groups {
		if group == nil || group.Envoy == nil {
			continue
		}
		g := &instanceGroup{
			autoPort:   group.Envoy.AutoPort,
			masterPort: group.Envoy.MasterPort,
			password:   "",
		}
		for name, inst := range instances.Instances {
			if inst == nil || inst.Group != groupName || inst.Status != "running" {
				continue
			}
			srv := pool.Servers[inst.Server]
			if srv == nil {
				continue
			}
			ep := envoyEndpoint{Address: srv.Endpoint, Port: inst.Port}
			if inst.Role == "master" && group.CurrentMaster == name {
				g.masterEndpoints = append(g.masterEndpoints, ep)
				g.password = inst.Password
			} else if inst.Role == "replica" {
				g.replicaEndpoints = append(g.replicaEndpoints, ep)
			}
		}
		groups[groupName] = g
	}

	return groups
}

func (s *Server) writeEnvoyConfig(config string) error {
	if err := os.MkdirAll(s.cfg.EnvoyDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(s.cfg.EnvoyDir, "envoy.yaml"), []byte(config), 0644)
}

// refreshEnvoy 拓扑变更后自动刷新 Envoy 配置（静默失败，不影响主操作）
func (s *Server) refreshEnvoy() {
	if s.cfg.EnvoyDir == "" {
		return
	}
	config, err := s.generateEnvoyConfig()
	if err != nil {
		s.log.Errorf("envoy config generate failed: %v", err)
		return
	}
	if err := s.writeEnvoyConfig(config); err != nil {
		s.log.Errorf("envoy config write failed: %v", err)
		return
	}
	s.log.Infof("envoy config updated: %s", fmt.Sprintf("%s/envoy.yaml", s.cfg.EnvoyDir))
	s.reloadEnvoy()
}

// reloadEnvoy 执行用户配置的重载命令（静默失败）
func (s *Server) reloadEnvoy() {
	if s.cfg.EnvoyReloadCmd == "" {
		return
	}
	out, err := exec.Command("sh", "-c", s.cfg.EnvoyReloadCmd).CombinedOutput()
	if err != nil {
		s.log.Errorf("envoy reload failed: %v, output: %s", err, string(out))
		return
	}
	s.log.Infof("envoy reloaded via: %s", s.cfg.EnvoyReloadCmd)
}
