package server

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/gin-gonic/gin"

	"gitlab.dev.ihuman.com/ihuman-infrastructure/dev/galaxy/common/redis-pilot/pkg/apitypes"
)

var envoyTmpl = template.Must(template.New("envoy").Parse(`# Auto-generated by redis-pilot server. DO NOT EDIT.
static_resources:
  listeners:
{{- range .Listeners }}
  - name: {{ .Name }}
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .Port }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: {{ .StatPrefix }}
          cluster: {{ .Cluster }}
          settings:
            op_timeout: 5s
          read_policy: {{ .ReadPolicy }}
{{- end }}

  clusters:
{{- range .Clusters }}
  - name: {{ .Name }}
    type: STRICT_DNS
    health_checks:
    - timeout: 1s
      interval: 5s
      unhealthy_threshold: 2
      healthy_threshold: 1
      custom_health_check:
        name: envoy.health_checkers.redis
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
          key: healthcheck
    drain_connections_on_host_removal: true
    load_assignment:
      cluster_name: {{ .Name }}
      endpoints:
      - lb_endpoints:
{{- range .Endpoints }}
        - endpoint:
            address:
              socket_address:
                address: {{ .Address }}
                port_value: {{ .Port }}
{{- end }}
{{- end }}
`))

type envoyListener struct {
	Name       string
	Port       int
	StatPrefix string
	Cluster    string
	ReadPolicy string
}

type envoyEndpoint struct {
	Address string
	Port    int
}

type envoyCluster struct {
	Name      string
	Endpoints []envoyEndpoint
}

type envoyData struct {
	Listeners []envoyListener
	Clusters  []envoyCluster
}

func (s *Server) envoyRouteUpdate(c *gin.Context) {
	config, err := s.generateEnvoyConfig()
	if err != nil {
		fail(c, http.StatusInternalServerError, err.Error())
		return
	}
	if s.cfg.EnvoyDir != "" {
		if err := s.writeEnvoyConfig(config); err != nil {
			fail(c, http.StatusInternalServerError, "write envoy config: "+err.Error())
			return
		}
	}
	ok(c, gin.H{"config": config})
}

func (s *Server) envoyConfig(c *gin.Context) {
	config, err := s.generateEnvoyConfig()
	if err != nil {
		fail(c, http.StatusInternalServerError, err.Error())
		return
	}
	ok(c, gin.H{"config": config})
}

// generateEnvoyConfig 根据 instances-state 和 pool-state 生成 Envoy 配置
func (s *Server) generateEnvoyConfig() (string, error) {
	instances, err := s.state.ReadInstances()
	if err != nil {
		return "", err
	}
	pool, err := s.state.ReadPool()
	if err != nil {
		return "", err
	}

	// 按实例组（主库名）聚合
	groups := s.buildInstanceGroups(instances, pool)

	data := envoyData{}
	for groupName, g := range groups {
		clusterName := "redis-" + groupName + "-cluster"
		statPrefix := "redis_" + strings.ReplaceAll(groupName, "-", "_")

		// 读写端口（read_policy: REPLICA，读走从库写走主库）
		if g.rwPort > 0 {
			data.Listeners = append(data.Listeners, envoyListener{
				Name:       "redis-" + groupName + "-rw",
				Port:       g.rwPort,
				StatPrefix: statPrefix,
				Cluster:    clusterName,
				ReadPolicy: "REPLICA",
			})
		}

		// 仅写端口（read_policy: MASTER）
		if g.woPort > 0 {
			data.Listeners = append(data.Listeners, envoyListener{
				Name:       "redis-" + groupName + "-wo",
				Port:       g.woPort,
				StatPrefix: statPrefix + "_wo",
				Cluster:    clusterName,
				ReadPolicy: "MASTER",
			})
		}

		// Cluster：包含主库和所有从库的 endpoint
		if len(g.endpoints) > 0 {
			data.Clusters = append(data.Clusters, envoyCluster{
				Name:      clusterName,
				Endpoints: g.endpoints,
			})
		}
	}

	var buf strings.Builder
	if err := envoyTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

type instanceGroup struct {
	rwPort    int // 读写端口
	woPort    int // 仅写端口
	endpoints []envoyEndpoint
}

// buildInstanceGroups 按主库聚合实例组，提取 Envoy 端口和后端地址
func (s *Server) buildInstanceGroups(instances *apitypes.InstancesState, pool *apitypes.PoolState) map[string]*instanceGroup {
	groups := make(map[string]*instanceGroup)

	for name, inst := range instances.Instances {
		if inst.Status != "running" {
			continue
		}
		if inst.Envoy == nil {
			continue
		}

		// 确定组名：主库用自己的名字，从库找主库名
		groupName := name
		if inst.Role == "replica" {
			// 从主库的 Replicas 列表反查
			for mName, mInst := range instances.Instances {
				for _, r := range mInst.Replicas {
					if r == name {
						groupName = mName
						break
					}
				}
			}
		}

		g, ok := groups[groupName]
		if !ok {
			g = &instanceGroup{}
			groups[groupName] = g
		}

		// 端口取主库的 Envoy 配置
		if inst.Role == "master" || inst.Role == "standalone" {
			if inst.Envoy.ReadWritePort > 0 {
				g.rwPort = inst.Envoy.ReadWritePort
			}
			if inst.Envoy.WriteOnlyPort > 0 {
				g.woPort = inst.Envoy.WriteOnlyPort
			}
		}

		// 后端地址
		srv := pool.Servers[inst.Server]
		if srv != nil {
			g.endpoints = append(g.endpoints, envoyEndpoint{
				Address: srv.Endpoint,
				Port:    inst.Port,
			})
		}
	}

	return groups
}

func (s *Server) writeEnvoyConfig(config string) error {
	if err := os.MkdirAll(s.cfg.EnvoyDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(s.cfg.EnvoyDir, "envoy-redis.yaml"), []byte(config), 0644)
}

// refreshEnvoy 拓扑变更后自动刷新 Envoy 配置（静默失败，不影响主操作）
func (s *Server) refreshEnvoy() {
	if s.cfg.EnvoyDir == "" {
		return
	}
	config, err := s.generateEnvoyConfig()
	if err != nil {
		s.log.Errorf("envoy config generate failed: %v", err)
		return
	}
	if err := s.writeEnvoyConfig(config); err != nil {
		s.log.Errorf("envoy config write failed: %v", err)
		return
	}
	s.log.Infof("envoy config updated: %s", fmt.Sprintf("%s/envoy-redis.yaml", s.cfg.EnvoyDir))
}
